#!/usr/bin/env bash
##
## pre: creation of certs
## openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
## and adding it to allowed certs
##
docker exec --user root deinebaustoffe_apache_1 mkdir -p -m 700 /etc/apache2/ssl/server.crt
docker exec -it deinebaustoffe_apache_1 a2enmod ssl

docker cp server.crt deinebaustoffe_apache_1:/etc/apache2/ssl/
docker cp server.key deinebaustoffe_apache_1:/etc/apache2/ssl

docker cp dev.conf deinebaustoffe_apache_1:/etc/apache2/sites-enabled/dev.conf

docker exec -it deinebaustoffe_apache_1 /etc/init.d/apache2 reload


## after: change websecure url to https
